(maint) prep for 0.114.0 release
puppetlabs/packaging pull request #1239
Opened 2024-01-24 23:39 UTC by e-gris

Please add all notable changes to the "Unreleased" section of the CHANGELOG.

2024-01-25 17:28 UTC, isaac-hammes requested changes

2024-01-25 17:28 UTC, isaac-hammes commented on CHANGELOG.md
> +## [0.114.0] - 2024-01-24
Looks good except the date. It is the 25th today.

2024-01-25 17:34 UTC, e-gris commented on CHANGELOG.md
> +## [0.114.0] - 2024-01-24
It was the 24th when I submitted it :*)

2024-01-26 17:09 UTC, e-gris commented
Let's wait until after the PE release to merge this.

2024-01-29 14:03 UTC, isaac-hammes approved these changes

2024-02-07 17:34 UTC, e-gris commented
We'll try this again elsewhere

2024-02-07 17:34 UTC, closed without merging